Completion async
sheeiavellie/go-yandexgpt pull request #10
Opened 2024-11-01 15:31 UTC by himasyuri

Issue: https://github.com/sheeiavellie/go-yandexgpt/issues/9

Added RunComletionAsync method.
Added GetOperationStatus for get status of async completion operation. In examples added examples using restructured library. 
Using yandex official documentation: 
Operation: https://yandex.cloud/ru/docs/foundation-models/text-generation/api-ref/Operation/get
CompletionAsync: https://yandex.cloud/ru/docs/foundation-models/text-generation/api-ref/TextGenerationAsync/completion

2024-11-05 15:42 UTC, sheeiavellie commented
Для начала стоит поменять префиксы у PR'а и коммитов в соответствии с https://www.conventionalcommits.org/ 
Следует использовать один из следующих префиксов:
 - fix
 - feat
 - chore
 - refactor
 - test
 - ci
В данном случае тут везде должно быть feat

2024-11-05 15:54 UTC, sheeiavellie requested changes

2024-11-05 15:54 UTC, sheeiavellie commented on response.go
> +	"net/http"
Здесь и дальше по файлу поехал формат

2024-11-05 15:54 UTC, sheeiavellie commented on request.go
> +  APIKey string `json:"yandexPassportOauthToken"`
Тут тоже поехал формат

2024-11-05 15:54 UTC, sheeiavellie commented on message.go
> +	Role         yandexGPTRole `json:"role"`
Тоже поехал формат

2024-11-05 15:54 UTC, sheeiavellie commented on examples/completionAsync/main.go
> +      fmt.Println("\n Chat answer: \n")
Тут и дальше тоже

2024-11-05 15:54 UTC, sheeiavellie commented on examples/completionAsync/main.go
> +	client := yandexgpt.NewYandexGPTClientWithAPIKey(os.Getenv("YAAPI_KEY"))
Думаю стоит не использовать os.Getenv для примера. Суть в том, чтобы скопировать себе код и быстро поменять строку, добавлять .env не так удобно.

2024-11-05 15:54 UTC, sheeiavellie commented on examples/completion/main.go
> +		ModelURI: yandexgpt.MakeModelURI(os.Getenv("CATALOG_ID"), yandexgpt.YandexGPT4ModelLite),
Думаю стоит не использовать os.Getenv для примера. Суть в том, чтобы скопировать себе код и быстро поменять строку, добавлять .env не так удобно.

2024-11-05 15:54 UTC, sheeiavellie commented on error.go
> +  Details DetailsResponse `json:"error.details"`
Формат съехал

2024-11-05 15:54 UTC, sheeiavellie commented on config.go
> -		BaseURL:    completionURL,
Т.к. BaseURL больше не используется, имеет смысл убрать его из структуры

2024-11-05 15:54 UTC, sheeiavellie commented on completions.go
> +	// TODO:
Это TODO можно в принципе убрать, но тут уже я проглядел

2024-11-05 15:54 UTC, sheeiavellie commented on client.go
> -	if c.config.ApiKey != "" {
А зачем убрали проверку для ApiKey? Там же все еще вроде как можно использовать ApiKey сервисного аккаунта

2024-11-05 15:54 UTC, sheeiavellie commented on client.go
> +
Лишние пробелы

2024-11-05 15:54 UTC, sheeiavellie commented on client.go
> +	req any,
Думаю можно оставить YandexGPTRequest, там же больше никакие другие типы с этим методом не используются

2024-11-05 15:54 UTC, sheeiavellie commented on auth.go
> +func (c *YandexGPTClient) UpdateIAMToken(ctx context.Context) error {
Тут и дальше плохие отступы

2024-11-05 19:41 UTC, himasyuri commented on client.go
> -	if c.config.ApiKey != "" {
Api key используется только один раз для получения IAM токена, который действует 12 часов

2024-11-05 21:56 UTC, himasyuri commented on client.go
> +	req any,
Для запроса IAM токена используется модель запроса YandexIAMRequest. Для этого был сменен входной тип на any. Также туда будет прилетать потом модель запроса на embeddings.

2024-11-07 10:30 UTC, sheeiavellie requested changes

2024-11-07 10:30 UTC, sheeiavellie commented on client.go
> +	req any,
Звучит неплохо, пусть тогда будет any.

2024-11-07 10:30 UTC, sheeiavellie commented on client.go
> -	if c.config.ApiKey != "" {
По доке API Key не используется для получения IAM токена. Для этого используется OAuth токен. Предлагаю дать возможность пользователю авторизовываться через API Key и через IAM токен (который можно получить различными способами, включая обмен не него OAuth токена). Соответственно, сюда можно добавить switch для API Key/IAM токена, чтобы задавать правильные хэдеры. Ну и не задавать никакие хэдеры, если делается запрос на получение IAM токена (они там не нужны).

2024-11-07 10:30 UTC, sheeiavellie commented on request.go
> +	APIKey string `json:"yandexPassportOauthToken"`
Соответственно здесь, нужно поменять APIKey на OAuth токен

2024-11-07 10:30 UTC, sheeiavellie commented on config.go
>  type YandexGPTClientConfig struct {
Предлагаю добавить сюда новое поле - OAuth токен

2024-11-07 10:30 UTC, sheeiavellie commented on auth.go
> +func (c *YandexGPTClient) UpdateIAMToken(ctx context.Context) error {
Предлагаю переименовать этот метод во что-то, что явно говорило бы про работу с OAuth токеном и запросу к API. Также предлагаю добавить метод по апдейту IAM без запроса (по сути дела сеттер). Так пользователь сможет обновлять токен сам, через свою инфраструктуру

2024-11-10 12:43 UTC, sheeiavellie approved these changes

2024-11-10 12:43 UTC, sheeiavellie commented on client.go
> +func NewYandexGPTClientWithOAuthToken(
Было бы славно добавить коммент сверху про то, что это за метод (по аналогии с другими конструкторами)

2024-11-10 12:43 UTC, sheeiavellie commented on completions.go
> +func (c *YandexGPTClient) RunCompletionAsync(
Здесь тоже было бы славно иметь коммент

2024-11-10 12:43 UTC, sheeiavellie commented on operations.go
> +func (c *YandexGPTClient) GetOperationStatus(
И сюда коммент

2024-11-10 12:43 UTC, sheeiavellie commented on config.go
> +func (c *YandexGPTClientConfig) SetIAMToken(iamToken string) {
И сюда тоже коммент

2024-11-11 13:58 UTC, merged