feat: embeddings
sheeiavellie/go-yandexgpt pull request #12
Opened 2024-11-11 13:50 UTC by himasyuri

Added functionality to get embeddings from Yandex GPT API.  Also added simple example how use it.
Source documentation: https://yandex.cloud/ru/docs/foundation-models/concepts/embeddings
https://yandex.cloud/ru/docs/foundation-models/embeddings/api-ref/Embeddings/textEmbedding

2024-11-11 16:24 UTC, sheeiavellie requested changes

2024-11-11 16:24 UTC, sheeiavellie commented on operations.go
> +func (c *YandexGPTClient) GetOperationStatus(
Тут было бы классно иметь коммент для метода GetOperationStatus

2024-11-11 16:24 UTC, sheeiavellie commented on examples/completionAsync/main.go
> +	for !isCompleted {
Предлагаю сделать через тикер и for select. Также в for select следует обработать момент с ctx.Done()

2024-11-11 16:24 UTC, sheeiavellie commented on embeddings.go
> +func (c *YandexGPTClient) GetEmbedding(
Сюда следует добавить коммент для GetEmbedding

2024-11-11 16:26 UTC, sheeiavellie commented
В целом круто, только незначительные правки. Также нужно будет решить конфликты - я сторонник git rebase -i

2024-11-11 22:44 UTC, himasyuri commented
> В целом круто, только незначительные правки. Также нужно будет решить конфликты - я сторонник git rebase -i

Не уверена, что правильно сделала обновление ветки после rebase, прошу проверить повнимательнее. Первый раз такое(

2024-11-13 16:59 UTC, sheeiavellie commented
@himasyuri нужно синкануть форк (подтянуть на main ветку в форке последние изменения (влитый пр)). Синкануть форк вроде можно прямо в гитхабе, а потом локально у себя git checkout main, git fetch origin и git pull. Потом git checkout embeddings. И уже можно запускать интерактивный ребейс через git rebase -i. В редакторе (если у вас настроен в баше стандартный эдитор) нужно будет удалить строки с ненужными коммитами (и оставить только коммиты по эмбеддингу, т.е. убрать нужно два верхних: 8075f82 и f04e1d2. Собственно, дальше просто поэтапно нужно будет разрешить конфликты (если они будут). В конце просто git push --force-with-lease

2024-11-13 17:03 UTC, sheeiavellie requested changes
Один момент в примерах, остальное мне нравится. Ну и разрешить конфликты (описал процесс в комменте выше, если будут вопросы по ходу - пишите!)

2024-11-13 17:03 UTC, sheeiavellie commented on examples/completionAsync/main.go
> +	client := yandexgpt.NewYandexGPTClientWithOAuthToken("OAUTH_KEY")
Тут все же должен быть OAUTH_TOKEN а не KEY

2024-11-13 22:48 UTC, himasyuri commented
Вроде rebase сделала, но не уверена. Но коммитов тех нет и конфликтов тоже

2024-11-13 22:56 UTC, sheeiavellie approved these changes

2024-11-13 22:56 UTC, sheeiavellie commented
> Вроде rebase сделала, но не уверена. Но коммитов тех нет и конфликтов тоже

Ну они есть ))
Там один добавляет пробелы, а другой убирает, но не критично

2024-11-14 09:17 UTC, merged